### ISSUE TITLE
Is `Nostalgist.pause()` an async function or not?

### ISSUE THREAD

**Issue by daGaiGuanYu** [arianrhodsandlot/nostalgist#27]
+ [async in docs](https://nostalgist.js.org/apis/pause/)
+ [sync in code](https://github.com/arianrhodsandlot/nostalgist/blob/fcd4ce646de25c540cd0a77cfd38f53ad04b5337/src/nostalgist.ts#L264)

**Comment by arianrhodsandlot** [comment]
Good catch! It should be a sync method, and the async examples are typos.
