### ISSUE TITLE
Additional libretro cores compatible with Nostalgist

### ISSUE THREAD

**Issue by gitGalu** [arianrhodsandlot/nostalgist#28]
Hi. There are few more cores that work great with Nostalgist (in addition to the ones you have uploaded to https://github.com/arianrhodsandlot/retroarch-emscripten-build/tree/main/retroarch ):

Atari 400 / 800 / XE / XL series
https://github.com/libretro/libretro-atari800
(If you try to compile this one and encounter any errors let me know, I may have some uncommitted changes)

Atari 2600 / VCS
https://github.com/libretro/stella2014-libretro 

Amstrad CPC series
https://github.com/libretro/libretro-crocods

To build the above - I cloned the projects and cd its directory, then
emmake make -f Makefile platform=emscripten
then changed the output filename to libretro_emscripten.bc and copied it to RetroArch directory, then (from this dir)
emmake make -f Makefile.emscripten LIBRETRO=corename -j all
(where corename is e.g. stella2014, atari800, crocods)

Apart from that, the EmulatorJS has a working Commodore Amiga core (that I cannot build at the moment due to emsdk issue?):
https://github.com/libretro/libretro-uae

**Comment by arianrhodsandlot** [comment]
Wow, that's great news! However the cores inside the repository [retroarch-emscripten-build](https://github.com/arianrhodsandlot/retroarch-emscripten-build) is not compiled by me. In fact, they are just copied from [the official buildbot of RetroArch](https://buildbot.libretro.com/stable/1.17.0/emscripten/) .
I may not have enough energy to maintain a set of additional cores other than the official ones. But if you would kindly like to help to add these Emscripten cores to RetroArch's buildbot, I will be glad to add them once they are released :)
