### ISSUE TITLE
BrowserFS deprecated

### ISSUE THREAD

**Issue by james-pre** [arianrhodsandlot/nostalgist#29]
Hi there, I'm the maintainer of BrowserFS. I've been going though the dependents of browserfs.

Please see the notice in the readme: https://github.com/jvilk/browserfs

Would you be interested in updating your project to use the updated fork, [ZenFS](https://github.com/zen-fs/core)?

**Comment by arianrhodsandlot** [comment]
Of course! I'll try to work on this migration recently.

**Comment by arianrhodsandlot** [comment]
It seems that [@zenfs/emscripten](https://github.com/zen-fs/emscripten) is still not ready while this project heavily relies on Emscripten. I'll keep an eye on ZenFS and continue the process of migration when the Emscripten backend is ready. This issue will remain open unless the migration is done. Thanks for your hard work :)

**Comment by dr-vortex** [comment]
@arianrhodsandlot, I'm still waiting on [DefinitelyTyped#69218](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69218) however I have done some preliminary work. Once the PR is merged I expect the Emscripten backend to be released within a week or two.

**Comment by arianrhodsandlot** [comment]
Since @zenfs/emscripten is still not available, I'm closing this issue. But I'm still open to do this migration when it's published and feel free to reopen the issue at that time :)

**Comment by james-pre** [comment]
@arianrhodsandlot,

v0.0.1 was released back in late May, but the CI workflow failed to run so the release was not actually published on NPM. It is available now.

**Comment by james-pre** [comment]
@arianrhodsandlot, It's been a while and `@zenfs/emscripten` is much more stable now.
