### ISSUE TITLE
When I already have a key, for example: input_user1_up:'w', how can I change the key to make the game work directly without having to start again  

### ISSUE THREAD

**Issue by Perfect-l** [arianrhodsandlot/nostalgist#32]

**Comment by Perfect-l** [comment]
nostalgist = await Nostalgist.launch({
    rom: data.rom,
    core: 'fceumm',
    state,
    resolveCoreJs(core, options) {
      return `https://res.fatfoxtab.com/public/res/player/nes/fceumm_libretro.js`
    },
    resolveCoreWasm(core, options) {
      return `https://res.fatfoxtab.com/public/res/player/nes/fceumm_libretro.wasm`
    },
    element: canvasRef.value,
    retroarchConfig: data.retroarchConfig,
  })

**Comment by arianrhodsandlot** [comment]
For now we do not support updating retroarch config while the emulator is running. I'm not sure if this can be done with the official retroarch emscripten build, and I'm going to do some research recently. But it maybe hard to achieve.

**Comment by arianrhodsandlot** [comment]
This seems to be impossible while using the official build of RetroArch... unfortunately.
