### ISSUE TITLE
audiocontext

### ISSUE THREAD

**Issue by zhangmenglong-github** [arianrhodsandlot/nostalgist#33]
Hello, I want to change some games to an online version. When synchronizing audio streams, I cannot obtain the audio stream. How can I read the audio stream data in the game?

**Comment by arianrhodsandlot** [comment]
A new API `getEmscriptenAL` has been added since v0.10.0. We can access some audio related properties from its return value. Could this fit your need?
```js
const AL = nostalgist.getEmscriptenAL()
console.log(AL.currentCtx， AL.currentCtx.audioCtx)
```
