### ISSUE TITLE
How to add loading as some of the retro games load slow

### ISSUE THREAD

**Issue by mmkmokaya** [arianrhodsandlot/nostalgist#34]
Hello,

Thank you for creating this awsome project but I have question.
When loading some NES game sometimes it load slow it just show black canvas I want to add loading screen how can I do that?

Thanks

**Comment by arianrhodsandlot** [comment]
Unfortunately we cannot detect has the game been launched with a meaningful image. Maybe you could use a `setInterval` to read the pixels from the canvas element to figure out is all the pixels black... though It's a bit tricky.
