### ISSUE TITLE
Frame callback? 

### ISSUE THREAD

**Issue by timotheeg** [arianrhodsandlot/nostalgist#37]
Hi there, would you have an example to have a callback for every frame? I'd like to interact with the emulator at every frame rendered. Thanks!

(specifically for the NES core)

**Comment by timotheeg** [comment]
Also related: is it possible to work with the command `READ_CORE_MEMORY`? 

I see it's not supported as a `RetroArchCommand`, but is there any way to make it work?

**Comment by arianrhodsandlot** [comment]
> would you have an example to have a callback for every frame

Unfortunately, it seems to be hard to implement, see https://github.com/arianrhodsandlot/nostalgist/issues/6#issuecomment-1762546748 .

> Also related: is it possible to work with the command `READ_CORE_MEMORY`?
> 
> I see it's not supported as a `RetroArchCommand`, but is there any way to make it work?

I've implemented sending command to RetroArch process, and states saving are implemented by this. But I have no idea how to get response from it in web browser. Any suggestions here? And if you've tried this, prs are always welcome:)
