### ISSUE TITLE
Feature: External/Manual Inputs

### ISSUE THREAD

**Issue by formula1** [arianrhodsandlot/nostalgist#4]
Looks like a cool project. One thing I noticed in the [instance methods](https://nostalgist.js.org/apis/#instance-methods) is that there are no manual input methods. Granted, keyboard and gamepad may be enough to control/play the game but a developer might want to have "on screen" controls for things like mobile devices. In addition, a player might want to customize the inputs of a gamepad to their liking or have something like a turbo (when a player doesn't want to mash a button) or toggle (so you don't have to hold down the run button in mario)

If you want to point me in the direction of where the inputs are handled I wouldn't mind taking a look at what I can do

**Comment by arianrhodsandlot** [comment]
Thanks for being interest in Nostalgist.js!

I assume you are talking about two topics: input mapping and input simulating.

## input mapping
RetroArch, the emulator program that Nostalgist.js is using under the hood, supports input mapping by default. So the only thing we need to do is configure it. We can use `retroarchConfig` like this:

```js
await Nostalgist.launch({,
  core,
  rom,
  retroarchConfig: {
    input_player1_up: 'w',
    input_player1_left: 'a',
    input_player1_down: 's',
    input_player1_right: 'd',
  }
})
```
Then we can use <kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> as a D-pad.

Related code:
+ https://github.com/libretro/RetroArch/blob/master/retroarch.cfg
+ https://github.com/arianrhodsandlot/nostalgist/blob/cbb6a03b6f47c01b4d98f31e7622494b76064e64/src/types/retroarch-config/skeleton.ts#L845-L1131

Additionally, some "core" may provide a certain configuation for "turbo". Taking the NES emulator fceumm as an example,
```js
await Nostalgist.launch({,
  core: 'fceumm',
  rom,
  retroarchCoreConfig: {
    fceumm_turbo_enable: 'Both',
  }
})
```
Then "x" and "y" on XBox controllers or corresponding keys on keyboard(<kbd>A</kbd> and <kbd>S</kbd> by default) will be "turbo b" and "turbo a"

Related document: [libretro/docs/docs/library/fceumm.md](https://github.com/libretro/docs/blob/47a664e11c8fab855812bf173e215f38609ffff9/docs/library/fceumm.md?plain=1#L246C10-L246C10)

Considering that not all users are familiar with how to configure RetroArch, perhaps I could add some sections on this topic to the website(seems that it's going to take a lot of effort... not sure how many people would like to dive into such depth), or at least some links.

## input simulating
To be honest, I have no idea about how to deal with this problem currently. User inputs are handled by RetroArch directly. I'm not sure will firing DOM keypress events manually work or not, but I'll try this when I have time.

.For reference, [EmulatorJS](https://github.com/EmulatorJS/EmulatorJS), another similar library seems to support this feature. But they do not provide APIs for this.

**Comment by arianrhodsandlot** [comment]
After trying for some time, I discovered that we can simulate keyboard input by invoking a method on Emscripten Module like this:
```js
const nostalgist = await Nostalgist.launch(/* options */)

const Module = nostalgist.getEmscriptenModule()

// press Enter for 10ms
Module.dynCall_iiii(471, 2, 10474576, 9909248)
await new Promise((resolve) => setTimeout(resolve, 10))
Module.dynCall_iiii(471, 3, 10474576, 9909248)
```

Hmmm.. it's so hard to understand!

I think I should implement some new APIs later, to make this easier. Maybe something like `nostalgist.press('xxx')`. I'll keep this issue open until it's usable. Thanks for your suggestion!

**Comment by formula1** [comment]
This looks above my paygrade, how did you find that?

`nostalgist.press('xxx')` sounds great. It would be nice if it would be something along the lines of
```typescript
nostalgist.press = (player: number, button: ButtonIdentifier, toggleValue: boolean)=>{
  // Module call here
}
```

An additional function regarding plugging in and unplugging controller would be nice also although that only really applies to nes/snes/genesis etc.

**Comment by arianrhodsandlot** [comment]
> how did you find that?

By using devtools' "event listeners" panel and debugging an emulator's js file like [fceumm_libretro.js](https://cdn.jsdelivr.net/gh/arianrhodsandlot/retroarch-emscripten-build@v1.16.0/retroarch/fceumm_libretro.js).

> An additional function regarding plugging in and unplugging controller would be nice

Do you mean [gamepadconnected event](https://developer.mozilla.org/en-US/docs/Web/API/Window/gamepadconnected_event)? And this is for browsers with real controllers. For emulators there doesn't seem to be such a thing. Abstract controllers seem to be always "connected" from emulators' perspective.

**Comment by arianrhodsandlot** [comment]
[It's here now🚀!](https://nostalgist.js.org/apis/press/)
